"""base

Revision ID: 5ab577a9406e
Revises: None
Create Date: 2013-05-22 20:36:48.318519

"""

# revision identifiers, used by Alembic.
revision = '5ab577a9406e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
